src/bufr2nc.py

These changes will enable the GSI reader flow. Leaving strings as doubles is a temporary fix so that downstream work can be enabled.

Clara's modifications to leave observation strings as doubles 

---

src/met-office/odbapi2nc.py

Do not delete relative humidity after converting it to specific humidity, so that both values get into IODA. Also changed select statement so that we are not "pruning" the data in the file so much. Instead, more missing values get converted.

Keep relative humidity, rework null/missing values

---

src/marine/altimeter/CMakeLists.txt
src/marine/altimeter/altimeter2ioda.py

Window used to select obs was twice as large as what was required.

Fixed the DA window size.

---

src/ODB2/Definitions/MO_amsua_Definition.yaml

Needed to change the variable names "solar_zenith/azimuth_angle" to "sol_zenith/azimuth_angle" in order to match the UFO operator code. This will need to be changed back if/when we go through and correct all non-CF variable names in UFO.

Change variable name to match ufo

---

README.md

After seeing that Anna had the same trouble running one of the scripts in this repo that I had a while back, I thought it would be good to add some clarification on how to install the scripts to the Readme file.
I also updated the Readme section regarding the odbapi2nc.py script, which should have been done in the same pull request that added the new ECMWF YAML files.

Update repo Readme file

---

README.md
src/ODB2/CMakeLists.txt
src/ODB2/odbapi2nc.py

We discovered that Met Office ODB2 reports contain a column called 'corvalue' which sometimes contains a bias-corrected observation value. This PR adds an option to the odbapi2nc import script that will allow users to import this bias-corrected value ('corvalue' column) instead of the un-corrected obs value ('obsvalue' column) if desired.
Also, while working on this enhancement, a problem was discovered with the ODB2 directory CMakeLists.txt file that was causing the ODB2 scripts to not get installed. (Not sure when this got broken since it used to work.) This is also fixed.

Add option to copy bias-corrected obs value

---

src/gsi-ncdiag/CMakeLists.txt
src/gsi-ncdiag/combine_conv.py.in
src/gsi-ncdiag/combine_geoval.py.in

Fixes bug in combine_conv that filtered out too many Tv observations (among other issues) with incorrect indexing.
Also adds combine_geoval.py which when using -f will simply concatenate all of the input GeoVaLs files (unique locations not working 100% correctly in this one, it's more difficult because of less metadata)

Add concatenation of GeoVaLs and Fix bug in combine_conv.py

---

src/ODB2/Definitions/MO_amsua_Definition.yaml
src/ODB2/odbapi2json.py.in
src/ODB2/odbapi2nc.py.in
src/ODB2/var_convert.py
test/testoutput/odb_sonde_16019.nc4

These changes to the ODB2-to-IODA converter are required due to the changes coming in PR's of the same branch name in IODA and [UFO](https://github.com/JCSDA/ufo/pull/327).
ODB2 files store pressure in Pa units, and the script no longer converts that to hPa when creating the corresponding IODA file.
Also, the CRTM variable names have been updated to reflect the change by UFO to using the CF names.

Required 'feature/use_pressure' changes.

---

.gitignore
src/marine/gmao_obs2ioda.py.in

Separate out the ioda files, one-per-obstype.
This was found to be necessary since missing values were difficult to filter out (a filter will need to be implemented).

Creates individual IODA files for each obs type

---

src/gsi-ncdiag/gsi_ncdiag.py
src/gsi-ncdiag/proc_gsi_ncdiag.py.in
src/gsi-ncdiag/subset_files.py

Currently, there are geoval and obs files used in UFO for development.  To implement the capability of data quality control (QC) in UFO, an additional set of information such as Jacobians and layer optical depth from the observation operator is required from GSI.  The capability of converting, subset, and write this additional set information from GSI diagnostic file to a separate file (obsdiatg) is added.

add obsdiag file containing diagnostics output from GSI for QC development in UFO

---

src/marine/emc_ice2ioda.py.in

The code had one bug and there was an issue with the time convention of the data. 
More specific: 
1. Loading the ioda-converter modules was transferred after appending the path.
2. The time convention was a four-digit integer, which is impossible for 12-9AM, making the  DateTime fail when 00:00. 
The code tested by converting successfully 30 days of observations.

Two bugs with emc_ice

---

test/iodaconv_comp.sh

So @travissluka and @mer-a-o - this is why the ioda-converters tests are failing in the intel containers.  Python wants to access the library ```libimf.so``` which is in the ```LD_LIBRARY_PATH```.  So, running the python scripts manually works fine but when the compare script runs them, it resets the paths and causes this error:
~~~~~
python: error while loading shared libraries: libimf.so: cannot open shared object file: No such file or directory
~~~~~
This bugfix fixes that so all ioda-converters tests now pass in the intel17 container.  I haven't tried yet with the intel 19 container.

Add exising LD_LIBRARY_PATH to bash script

---

README.md
buildspec_intel.yml

This PR fixes the bug in ```buildspec_intel.yml```. I updated the Intel container on AWS ECR with the latest version of Docker container that @mmiesch provided. This should fix the problem build failure in Intel containers.

Bugfix in aws intel

---

src/gsi-ncdiag/gsi_ncdiag.py
test/testinput/gsidiag_amsua_aqua_radiance_test.nc
test/testoutput/amsua_aqua_obs_2018041500.nc4

**Enhancements made in this PR:**
(1) Added handling of sea surface temperature data
(2) Include OMP sensors for ozone data type
(3) Updated list of observation types (bufr types) for GPS and SST
(4) Added missing units for some variables
(5) Enhanced the capability of adding test fields to handle data with channel dimension
**Issues and related bug fix:**
The initial observation error values stored in @ObsError group were not correct for all-sky radiance and ozone data.
**Issues:**
- (1) The clear-sky observation error values were used for the all-sky case. While the clear-sky errors are assigned to constant for each channel globally, the all-sky errors for each channel vary at each observation location.  
- (2) The final observation error values (adjusted values) were stored in …

Add capability to handle NCEP operational observations

---

src/gsi-ncdiag/gsi_ncdiag.py
src/lib-python/ioda_conv_ncio.py
src/marine/argoClim2ioda.py.in
src/marine/cryosat_ice2ioda.py.in
src/marine/cryosat_ice2ioda_DBL.py.in
src/marine/emc_ice2ioda.py.in
src/marine/gds2_sst2ioda.py.in
src/marine/gmao_obs2ioda.py.in
src/marine/godae_profile2ioda.py.in
src/marine/godae_ship2ioda.py.in
src/marine/godae_trak2ioda.py.in
src/marine/hgodas_adt2ioda.py.in
src/marine/hgodas_insitu2ioda.py.in
src/marine/hgodas_sst2ioda.py.in
src/marine/rads_adt2ioda.py.in
src/marine/smap_sss2ioda.py.in
test/testoutput/amsua_aqua_obs_2018041500.nc4
test/testoutput/argoclim.nc
test/testoutput/cryosat2_L2.nc
test/testoutput/cryosat2_L2_DBL.nc
test/testoutput/gds2_sst_l2p.nc
test/testoutput/gds2_sst_l3u.nc
test/testoutput/godae_prof.nc
test/testoutput/godae_ship.nc
test/testoutput/godae_trak.nc
test/testoutput/hgodas_insitu.nc
test/testoutput/hgodas_sst.nc
test/testoutput/rads_adt.nc
test/testoutput/sfc_tv_obs_2018041500.nc4
test/testoutput/smap_sss_rss.nc

List of work performed in this PR:
(1) Removed the use of nrecs from IODA obs file (see changes in gsi_ncdiag.py and ioda_conv_ncio.py)
(2) Updated all python scripts under marine directory according to changes in (1)
(3) Updated all related output test observation files (test/testoutput) according to changes in (1) and confirmed that the nrecs were removed.

Removed the use of nrecs in IODA obs files

---

src/gsi-ncdiag/combine_conv.py.in
src/gsi-ncdiag/subset_files.py

This is a following-up PR for PR #256 
In PR#256, we removed the use of nrecs from IODA obs files converted from GSI diagnostic files.
In this PR, the use of nrecs is removed from the **combined** and **subse**t IODA obs files.
The following two python scripts were modified:
- combine_conv.py
- subset_files.py.in

Remov the use of nrecs in the combined and subset obs files

---

src/gsi-ncdiag/gsi_ncdiag.py
test/testoutput/amsua_aqua_obs_2018041500.nc4

This is a follow-up PR for previous PR #257 
Three things:
(1)  A bug that prevented the @TestReference group written to obs file was found.
The list variable "test_fields" should be "test_fields_"
(2) Added units to variables in @TestReference group for radiance data
(3) Updated test output file for amsua_n19 obs file since units were added to variables in test fields.

Bug fix for test fields  

---

src/gsi-ncdiag/gsi_ncdiag.py
src/lib-python/ioda_conv_ncio.py

The ObsBias group is specific to the VarBC in UFO.
To avoid conflict, the **ObsBias** has been changed to **GsiObsBias** in gsi-ncdiag.

Change ObsBias to GsiObsBias

---

src/gsi-ncdiag/combine_conv.py
src/gsi-ncdiag/test_gsidiag.py

The `combine_conv.py` was taking several minutes to combine the individual instruments for each platform into final IODA files.  This PR address several performance bottlenecks and the speed of conversion is now just a few seconds.  The files produced should be bit-for-bit identical.

Improve speed of gsi NCDIAGS IODA obs combining by 10x-30x

---

src/lib-python/ioda_conv_ncio.py

This hopefully fixes `UnicodeEncodeError` and `UnicodeDencodeError` for station ids in some conventional obs produced during the GSI NCDIAGS conversion process.
Honestly, this particular part of the code this patch addresses is a mess and whatever is happening is likely wrong or very inefficient or both, and will need to be eventually refactored to deal with strings in a sane manner.   For now, I'm crossing my fingers that this patch works and isn't papering over any more serious problems.  At least it is now not crashing.

Fix unicode encoding errors for station id

---

.gitignore
src/gsi-ncdiag/gsi_ncdiag.py

Fix ncdiags converter utf-8 conversion errors.   Convert to a string before passing to `netCDF4.stringtochar()` which doesn't understand non-utf8 compliant codes.
This appears to be a new problem starting with data from `20200427_1800Z` cycle.  This is a quick and dirty fix.  I'm curious to actually look over this code a bit more in detail.  Hopefully, there are not more problems like this lurking.  I'm not sure why what could be as simple as a list of strings is formatted as a 2d numpy array of null-terminated byte sequences of length 1.  We'll need to review this bit again when I have more time.
Symptom is:
```molah@s4-submit ~/.jedi-rapids/scratch/obs-gsi-ingest/2020042800/master/2020042800_obs.tar $ ~/.jedi-rapids/prefix/intel17/bin/test_gsidiag.py  -o …
```

Fix ncdiags converter utf-8 conversion errors??

---

src/odc/nc2odb.py

This PR cleans up the nc2odb.py script which had a leftover ``import codyssey`` command but was not using that package. This breaks when we go to the release versions of odc and pyodc since the package names in pyodc changed.

Removed unused imported package (codyssey)

---

src/marine/godae_profile2ioda.py.in

This PR fixes a new code style error (E741) where the variable 'l' (lower case ell) was being flagged as an ambiguous variable name. The idea behind the new check is to flush out single letter variable names that look like numerical digits (in this case lower case ell looks like the digit one).
Closes #282

Fixed coding norm error that surfaced when pycodestyle was upgraded

---

src/gnssro/gnssro_bufr2ioda.f90
test/testoutput/gnssro_kompsat5_2018041500.nc4

The azimuth angle QC check is removed in GNSSRO IODA convertor because operators should check the azimuth angle when needed. Actually azimuth angles are only required in 2D operators.  RO data without azimuth angle should not be rejected in data processing.
https://github.com/jcsda/aop20/issues/58

remove azimuth angle QC in convertor

---

src/gsi-ncdiag/combine_conv.py

This fixes a bug where if the `MetaVarData` is empty for some meta variables, the concatenation process will break.  Instead of keeping around all the broken metavariables, I am deleting those that are empty/erronous.  This seems to fix the problem with the `2020061506_obs.tar` and later gsi ncdiags conversion.  I am having some difficulty fully testing due to unrelated updates with fv3-bundle which are preventing a jedi-rapids build from completing.  I am about 90% sure this should be working, but let's hold off on merge until I get the jedi-rapids build working again.

Remove MetaVars which have empty data in ncdiags from lists in combine_conv.py

---

src/gsi-ncdiag/gsi_ncdiag.py

This fixes issue #301, where the units were changed globally. They are in ppmv for radiance geovals.

Revert units for radiance back to ppmv.

---

src/lib-python/ioda_conv_ncio.py

While testing performance of @CoryMartin-NOAA 's new `tropomi_no2_nc2ioda.py` in PR #300, I noticed that the majority of the time was spent in `NcWriter::ConvertToTimeOffset` which parses datetime strings in ioda format and converts to the decimal hour float32 offset used in the `Time@MetaData`.  Since this was bottlenecking the whole converter there was not much sense in trying to optimize the tropomi converter itself any further until this was addressed.  
Now I think this PR should remove the bottleneck and allow further performance profiling and improvements.
Percent of total runtime spent in `NcWriter::ConvertToTimeOffset` (with 45MB NetCDF datasource):
* Original: `2.67 s / 3.38 s = 79%` ![tropomi_orig_ConvertToTimeOffset](https://user-images.githubusercontent.com/14096120/89942982-b …

Performance improvement for NcWriter DateTime conversions

---

CMakeLists.txt

jedi-build manages binary .tar.gz packages, and this patch helps ioda-converters to produce these packages.
You can now use the ```make package``` command.

CPack support for jedi-build

---

src/gsi-ncdiag/gsi_ncdiag.py

There is a mismatch between standard GSI (hPa) and our "modified" GSI (Pa) in units of pressure, both for use as a coordinate (e.g. radiosondes) and for surface pressure obs.
This will check to see if the fields for GeoVaLs exist, and if so, do no unit conversion, otherwise it will convert from hPa to Pa.
Once @emilyhcliu and I have a new GSI GeoVaL generator, we will make sure we 1) remove the unit conversions in the source code and 2) modify the ioda-converters to handle all unit conversions.

Bugfix for pressure units

---

src/gsi-ncdiag/gsi_ncdiag.py

The modified version of GSI to produce GeoVaLs uses "Input_Observation_Error" rather than "Inverse_Observation_Error".
For those who just want to produce IODA obs files using GSI, a standard version of GSI will only have Inverse_Obs_Error.
This PR will default to Input, and if it doesn't exist, use Inverse (and compute the inverse of it).

Fix for using GSI-ncdiag converter with standard versions of GSI

---

src/ssec/giirs_ssec2ioda.py

The `giirs_ssec2ioda.py` executable reads in a sequence of GIIRS NetCDF data files and accumulates the combined data into a single IODA file.  The first GIIRS file read in is used to initialize the metadata variables that will be sent to the `NcWriter` object.
Some metadata variables are optional and don't occurr in every GIIRS file, primarily the `Cloud_Fraction` variable.  If the first file read in does not contain `Cloud_Fraction` or any other optional variable, the output numpy array is never initalized and the conversion will error out if a subseqent file then has this variable.
This PR seperates the metadata variable initalization into a private method and calls it as needed if a new variable is discovered in a later file.
This is a blocker for the NRT GFS website workflow, so I am …

Fix GIIRS IODA metadata initalization if not all variables are in first file

---

test/CMakeLists.txt
tools/iodaconv_comp.sh

This PR adds the ability to pass in a relative tolerance value to iodaconv_comp.sh (nccmp inside) when checking the contents of netcdf4 files. The need for this became apparent when the GIIRS test started failing on my iMac (despite passing in CI testing).
- fixes #353 
None
None

Added relative tolerance spec to nccmp calls.

---

src/bufr/CMakeLists.txt

Fix a typo in variable name for bufr CMake header install directory.
Bad variable name causes headers to attempt to install to the root directory.
None
None

Fix typo that is causing bufr headers to install to the root directory.

---

src/satbias/CMakeLists.txt

GsiSatBiasReader.cpp and GsiSatBiasReader.h are the names of the files (note the camel case)
I suspect this passed for @srherbener because MacOS is case-insensitive?
Fixed so it will compile on Hera (and presumably elsewhere)

Fix case sensitivity issue in GsiSatBias

---

src/gsi-ncdiag/gsi_ncdiag.py

Addition of the LaunchTime float variable in the dictionary of `gsi_ncdiag.py.` This is intended for radiosondes. Knowledge of the sondes launch time allows to uniquely identify all individual data points, spread over the processors in JEDI, belonging to the same sounding. This is helpful to reproduce GSI observation error inflation that applies when several data points of the same soundings are found within the same grid box at the same time.  
Provide a detailed description of what this PR does.
The entry `LaunchTime` is added to the dictionary of `gsi_ncdiag.py` as a float with units in hours. When the variable LaunchTime is present in `GSI_diags` conventional files, the change will insure that the following variable is created in the corresponding `obs` file upon conversion:
```
float …
```

Addition of LaunchTime (float, unit: hours) to the dictionary of gsi_ncdiag.py.

---

src/satbias/SatBiasConverter.cpp

This is a small fix to the bias files. See title.
Once this PR is in, satbias files should be regenerated for all instruments. ufo develop can work with either the existing files or the new ones, but the ioda sprint needs the new files.

Assign dimensions to all variables in satbias files

---

src/gsi-ncdiag/gsi_ncdiag.py

Some of the metadata for GMI is channel dependent. Channels 1-9 has one value while channels 10-13 has another. In this PR a second variable is added for these metadata variables appended with "1" and filled with the values for the channel 10-13.
Thanks at @CoryMartin-NOAA for the suggestion of how to add this.
Enough data in GMI files to replicate the GSI with ioda converted gsi-diags.

Add channel dependent metadata for GMI

---

README.md

This PR replaces the build instructions in the top level README.md file with newer instruction using ioda-bundle. This also deletes the obsolete bufr2nc.py documentation.
The new instructions are correct.
None
None
None

Update README.md with instructions on how to build ioda-converters

---

src/gsi-ncdiag/gsi_ncdiag.py

Changes GSI converter to remove processing of 134/234 (TAMDAR) as they are never permitted to be shared with non-authorized users. This will normally be handled upstream but this will ensure that these observations do not go into IODA formatted files.
Closes #483 
None

Changed converter to not process obstype 134/234

---

CI/buildspec_clang.yml
CI/buildspec_gnu.yml
src/bufr/BufrParser/BufrCollectors/BufrIntCollector.cpp
src/bufr/BufrParser/BufrCollectors/BufrRepCollector.cpp
src/bufr/BufrParser/BufrParser.cpp

This PR adds in Ron's workaround for handling the two namings for the bufr interface include file. This has been tested on my iMac using the old and new versions of the NCEPLIBS-bufr library so this should enable developers to continue their work using either library while we get the test container issue sorted out.
None
The develop version of the EMC bufr converter builds and tests pass with either of the old ore new version of the NCEPLIBS-bufr library.
None
None
None

Added code to handle the two namings of the bufr interface include file.

---

src/bufr/IodaEncoder/IodaDescription.h

Switched usage of enable_if_t to enable_if in order to be compliant With c++ 11.
#496

Switch usage of enable_if_t to enable_if to support C++ 11

---

src/marine/CMakeLists.txt
src/marine/smos_sss2ioda.py
test/CMakeLists.txt
test/testinput/SM_REPR_MIR_OSUDP2_20100601T000131_20100601T001849_662_120_1.nc
test/testoutput/smos_sss_l2.nc

This PR adds a ioda-converter for SSS SMOS L2 data from ESA (smos_sss2ioda.py)
The ioda-converter reads the date from each data (nc) file per day since there is no "time" variable provided.
The SMOS ESA data is available from 20100601
What problem does it fix? What new capability does it add?
Adds capability to use SMOS SSS data
[See the JEDI Documentation](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/pullrequest.html) for further information.
- fixes #489 >

ioda-converter for SMOS SSS L2 from ESA

---

src/satbias/GsiSatBiasReader.cpp

Certain sensors/platforms would fail on Orion when trying to generate satbias IODA files (atms for example).
Two bugs were found:
- file close was located outside of the if that checks if the file is open
- nobs(jchan) was outside of an if statement, and thus, for all lines in the input file after the sensor of interest, the value of jchan would be greater than the size of nobs, on some machines I guess this isn't a problem, but it is (I think) overwriting unallocated memory, which led to downstream problems in the code on Orion. 
These changes should fix these bugs. Thanks to @fabiolrdiniz for tag teaming this debugging effort and testing the fix.
I do no think this was associated with an issue but was found as part of JEDI-GDAS data preparation testing.

Bug fix for certain sensors on Orion

---

src/gsi-ncdiag/gsi_ncdiag.py

Our old feature/files_for_jedi wrote out 'Forecast_adjusted', etc. explicitly, but in GSI by default, only Obs_Minus_Forecast_adjusted and Observation are written to the netCDF diag files.
This PR will compute GsiHofX from O-(O-F) if F is not already present in the GSI diag file.
It was noticed that the IODA formatted files we prepared for the obs team for JEDI-GDAS did not have GsiHofX in them, this should address that.

Add support for GsiHofX from standard GSI output

---

.github/ISSUE_TEMPLATE/bug-report.md
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/general-issue.md

I remembered this morning that the organization-level github issue templates were not working with ZenHub.  So, to implement the issue templates in ZenHub, I believe we have to do it in each repository.
So, this implements the issue templates for ioda-converters.
N/A
When a user opens an issue in the ioda-converters repo using ZenHub, he or she will be able to use a general or bug template.
None
None
None

add issue template

---

src/bufr/IodaEncoder/IodaEncoder.cpp
src/satbias/SatBiasConverter.cpp

This PR replaces the syntax for declaring new dimensions in develop (shared_ptr method) with the new syntax in feature/ioda-v2 (no shared_ptr, simpler interface).
- fixes #505
The feature/ioda-v2 branch in ioda-converters compiles successfully. Note that you need to use the feature/ioda-v2 branch in ioda for this to work properly.
None
None
None

Move new dimension declarations to new ioda-v2 syntax

---

doc/bufr_table_samples/adpupa.nc002001.bufr.table.txt
doc/bufr_table_samples/adpupa.nc002002.bufr.table.txt
doc/bufr_table_samples/adpupa.nc002003.bufr.table.txt
doc/bufr_table_samples/adpupa.nc002004.bufr.table.txt
doc/bufr_table_samples/adpupa.nc002005.bufr.table.txt
doc/bufr_table_samples/adpupa.nc004005.bufr.table.txt

New six BUFR tables for each subset of the ADPUPA data for bufr2ioda conversion.
People can have access of these tables and find important Mnemonics informations. 
There is no dependencies. 
No impact
No test data

New BUFR tables for each subset of the ADPUPA data 

---

src/bufr/CMakeLists.txt

This PR adds code to make sure the include paths are set properly for building the BUFR converter. This change was necessary to get the build to work properly in the new ecbuild 3.6.1 environment. I have tested both in the current (ecbuild 3.3.2) environment and the new ecbuild 3.6.1 environment with these changes on my Macs and the build completes successfully and all tests pass in both cases.
None
Tests pass in both ecbuild 3.3.2 and ecbuild 3.6.1 environments.
None
Please list the other repositories (if any) that this PR will require changes in (example below)
None
None

Fix to get working with ecbuild 3.6.1

---

src/gsi-ncdiag/gsi_ncdiag.py

This PR adds the conversion of "avhrr3" named GSI ncdiag files into observation and geoval file.  
Provide a detailed description of what this PR does.
The "avhrr3" instrument has been added to the list of radiance sensors for GSI ncdiags input files, so that GSI-generated diag files "avhrr3" can be processed and "avhrr3" observation and geoval files can be created. 
What problem does it fix? What new capability does it add?
This solves the naming convention problem noticed in the JEDI GDAS experiments.
https://github.com/JCSDA-internal/experiments/issues/15
ioda-converters were tested with "avhrr" and "avhrr3" input files and generated the proper output file name and content. 
What does it mean for this PR to be finished?
[GSI](https://github.com/JCSDA-internal/GSI) ncdiag scripts will …

Addition of avhrr3 naming for GSI ncdiag files

---

doc/bufr_table_samples/adpsfc.nc000000.bufr.table.txt
doc/bufr_table_samples/adpsfc.nc000001.bufr.table.txt
doc/bufr_table_samples/adpsfc.nc000002.bufr.table.txt
doc/bufr_table_samples/adpsfc.nc000007.bufr.table.txt
doc/bufr_table_samples/adpsfc.nc000010.bufr.table.txt
doc/bufr_table_samples/adpsfc.nc000011.bufr.table.txt
doc/bufr_table_samples/adpsfc.nc000100.bufr.table.txt
doc/bufr_table_samples/adpsfc.nc000101.bufr.table.txt
doc/bufr_table_samples/adpsfc.nc000102.bufr.table.txt
doc/bufr_table_samples/aircft.nc004001.bufr.table.txt
doc/bufr_table_samples/aircft.nc004002.bufr.table.txt
doc/bufr_table_samples/aircft.nc004003.bufr.table.txt
doc/bufr_table_samples/aircft.nc004004.bufr.table.txt
doc/bufr_table_samples/aircft.nc004006.bufr.table.txt
doc/bufr_table_samples/aircft.nc004009.bufr.table.txt
doc/bufr_table_samples/aircft.nc004010.bufr.table.txt
doc/bufr_table_samples/aircft.nc004011.bufr.table.txt
doc/bufr_table_samples/aircft.nc004103.bufr.table.txt

There are 9 different subtypes of AIRCFT and ADPSFC data. Each has their own unique sequence of mnemonics. These 18 bufr tables document the sequences and mnemonics.
The bufr tables may now be easily accessible to those that need them.
A number of issues were written to gather information and write these bufr tables. The tables are documented as text files and as text in the following issues
For adpsfc: #549 #548 #547 #546 #545 #544 #543 #542 #541 #540 
For aircft: #572 #571 #570 #569 #568 #567 #566 #565 #564 #563 
None
None
None

add adpsfc and aircft individual bufr tables to ioda-coverters

---

src/gnssro/gnssro_bufr2ioda.f90
src/gnssro/gnssro_gsidiag2ioda.f90
test/testoutput/gnssro_kompsat5_2018041500.nc4

This PR deletes extra dimensions in the output IODA file header because IODA2 can not handle dimensions other than "nlocs".
- fixes https://github.com/JCSDA-internal/ufo/issues/1309
- fixes https://github.com/JCSDA-internal/ufo/issues/1310

update gnssro fortran converters

---

tools/run_satwnds/satwnds_new_subset_template.yaml
tools/run_satwnds/satwnds_old_subset_template.yaml

See Issue [#587](https://github.com/JCSDA-internal/ioda-converters/issues/587)
We are adding global attribute _bufr_verson_ (BUFR sequence version) to the ioda output from bufr2ioda, allowing us to distinguish between two BUFR versions used for AMVs (satellite winds).
Later, UFO filters could read  bufr_verson and make quality control decisions.
This PR adds code to:
ioda-bundle/iodaconv/tools/run_satwnds/satwnds_old_subset_template.yaml
ioda-bundle/iodaconv/tools/run_satwnds/satwnds_new_subset_template.yaml
to add the global attribute.
- fixes #<587>
The ioda output will show bufr_version:
// global attributes:
string :_ioda_layout = “ObsGroup” ;
:_ioda_layout_version = 0 ;
string :bufr_version@MetaData = “310077" ;  
(or "310014")
None
- …

Add bufr_version as global attribute to bufr2ioda output (for AMVs only)

---

CI/buildspec_clang.yml
CI/buildspec_gnu.yml
CI/buildspec_intel.yml
test/CMakeLists.txt

This PR enables BUILD_PYTHON_BINDINGS by default. This is done because the python bindings (ioda engines Python API) recently became a dependency for ioda-converters.
- fixes #613
All ioda-converters tests pass.
None

Enable BUILD_PYTHON_BINDINGS by default

---

src/gsi-ncdiag/gsi_ncdiag.py
test/testoutput/amsua_aqua_obs_2018041500.nc4
test/testoutput/satwind_obs_2018041500.nc4
test/testoutput/sfc_tv_obs_2018041500.nc4

Adds a new variable, GsiEffectiveQC, to the GSI ncdiag output.
- fixes #633 
Once Obs team and EMC can verify through a spot check that the 'good' obs have a value of 0, and all else, 1.
None
None

Add GsiEffectiveQC variable

---

src/lib-python/ioda_conv_engines.py

This is a companion PR to jcsda-internal/ioda/pull/500 that is necessary due to the reorganization of the ioda python modules.
Accompanies changes in jcsda-internal/ioda/pull/500 that contribute to fixing the issue jcsda-internal/ioda/issues/463
Pybind11 and miniconda successfully build together.
The issues with multiple versions of libraries (such as hdf5) at runtime are not completely addressed by this PR. If the library versions match between miniconda and jedi-stack, then there will be no issues at runtime. The piece in getting the library versions all sync'd up is outside the scope of the ioda-converters repo.
The homebrew python and jedi-stack have matching libraries on my MacBook so there are no runtime issues. Ie, the openssl and homebrew python have matching versions for openssl …

Link to python libraries in "module" mode instead of "embed" mode

---

src/goes/goes_converter.py

This pull request repairs a bug in the GOES-16/17 converter in three list initializations in the function `_create_metadata_solar_zenith_angle_variable` in the `GoesConverter` class.

Repaired list initialization in GOES-16/17 IODA converter.

---

src/marine/hgodas_adt2ioda.py
test/CMakeLists.txt
test/testinput/hgodas_adt.nc
test/testoutput/hgodas_adt.nc

Upgrades the marine/hgodas_adt2ioda convert to use the new ioda v-2 interface and adds relevant tests and testdata.
- fixes #646

Upgrade hgodas_adt2ioda to use ioda-v2 and add tests

---

src/chem/airnow2ioda-nc.py
test/testoutput/airnow_2020081306.nc

*(Instructions: replace text in this and all sections with your own text)*
Provide a detailed description of what this PR does.
remove the duplicated observation records
change variable name of pm25_tot to pm25
add real station_elevation (meter) in place (the existing one uses dummy value)
What problem does it fix? What new capability does it add?
remove the duplicated record,  add the real station_elevation. The variable name change is for the new AIRNow UFO 
https://github.com/JCSDA-internal/ufo/pull/1666
[See the JEDI Documentation](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/pullrequest.html) for further information.
N/A
If this does not close an existing issue, then [be sure to …

upgrade airnow2ioda converter

---

doc/bufr_obs_samples/gnssro_bufr_sample.txt
doc/bufr_table_samples/gnssro_bufr_mnemonics.txt
test/CMakeLists.txt
test/testinput/gnssro_2020-306-2358C2E6.bufr
test/testinput/gnssro_wmoBUFR2ioda.yaml
test/testoutput/gnssro_2020-306-2358C2E6.nc

Add capability to convert WMO BUFR formatted GNSSRO data to IODA directly with more flexible bufr2ioda application instead of fortran converter.  One problem is the Quality Flags remain a 16-bit integer whereas the existing IODA file does need the derived value of ascending and descending pass (bit position 3).  Therefore more processing of the quality flags will be needed within UFO.  This PR also adds documentation for BUFR mnemonics and sample obs into the doc subdirectory for additional data usage if needed.
This item in particular does not have a corresponding issue number but moving towards BUFR-2-IODA in general needs to include as many data types as possible.
Successful completion of ctest and useful IODA (v2) file for use within UFO (QC and subsequent steps).
No dependencies.
No …

Add ability to convert GNSSRO data in WMO-formatted BUFR to IODA (v2) output

---

doc/bufr_obs_samples/satwind_EUMet_bufr_sample.txt
doc/bufr_table_samples/satwind_EUMet_mnemonics.txt
doc/bufr_table_samples/satwind_Himawari_bufr_sample.txt
doc/bufr_table_samples/satwind_Himawari_mnemonics.txt
test/CMakeLists.txt
test/testinput/satwind_EUMet_wmo.bufr
test/testinput/satwind_EUMet_wmoBUFR2ioda.yaml
test/testinput/satwind_Himawari_wmo.bufr
test/testinput/satwind_Himawari_wmoBUFR2ioda.yaml
test/testoutput/satwind_EUMet.nc
test/testoutput/satwind_Himawari.nc

This PR adds 2 observation types of satellite atmospheric motion vectors (AMV) from EU_Met and Himawari in WMO-formatted BUFR to convert to IODA. Included in the PR are a sample of a single observation of each type, the BUFR table (in doc folder) and sample print of the bufr contents (doc folder).
Closes #717 
Working ctests
None, although #714 might need to precede this PR since there could otherwise appear to be a merge conflict with test/CMakelists.txt file since they are added subsequently in same file location as that PR.
No impacts to other repos.

Add support for WMO-formatted BUFR files of 2 satellite wind (AMV) sources: EU_MetSat and Himawari

---

src/marine/CMakeLists.txt
src/marine/godae_bgc_argo2ioda.py
test/CMakeLists.txt
test/testinput/godae_bgc_argo.nc
test/testoutput/godae_bgc_argo.nc

This PR adds a python script to "marine" that reads in historical or near real-time biogeochemical (BGC) Argo profiles from godae ftp server and converts to a unified format that supports IODA v2.
A small example data file (a single pair of upward and downward profile) was fetched from https://biogeochemical-argo.org/data-access.php (godae ftp server). This portal provides historical and near real-time (w/ approximately 24 hours delay) Argo profiles in .nc format from participating Argo fleets.
- fixes #726 
- fixes soca-science issue [#383](https://github.com/JCSDA-internal/soca-science/issues/383)

New marine converter: godae BGC-Argo profiles

---

src/conventional/decode_bufr_LDM_raob.py

This PR is proposing to merge changes into the `feature/generic-bufr-LDM-raob-decode_fix4norms` branch (see https://github.com/JCSDA-internal/ioda-converters/pull/734).
CI tests failing are not related to the changes proposed in this PR. They are due to missing the `eccodes` package, see below:
```
951 | 72 - test_iodaconv_generic_bufr_raob (Failed)
952 | 73 - test_iodaconv_generic_bufr_raob_multi_files (Failed)
```
None
Fix the coding norms issue.
None
None

Fix for norms under the feature/generic-bufr-LDM-raob-decode branch

---

test/CMakeLists.txt
test/testinput/aircar_BUFR2ioda.yaml
test/testinput/amdar_wmoBUFR2ioda.yaml
test/testinput/gdas.aircar.t00z.20210801.bufr
test/testoutput/amdar_wmo_multi.nc
test/testoutput/gdas.aircar.t00z.20210801.nc

This is rather similar to what is performed with amdar_wmoBUFR2ioda.yaml, except that the input data are reprocessed NCEP-EMC GDAS BUFR files available from NOMADS and also NCAR-RDA (ds351.0) in files with reference name of gdas.aircar.(date).bufr in place of WMO-formatted BUFR.  The mnemonics are somewhat different with these files compared to WMO BUFR data.  The mnemonics are listed/described as part of ```doc/bufr_table_samples/aircft.nc004004.bufr.table.txt``` because it is the subset that is referred to with NC004004 only.  Various other aircraft data (AIREPs, PIREPs, etc.) are found in other subsets and the gdas.aircft.(date).bufr files, which would need to be split out into separate chunks for different yaml files because of using different mnemonics depending on the subset of …

Add BUFR-to-IODA support for Aircraft data: gdas.aircar files (similar to amdar_wmoBUFR2ioda.yaml)

---

src/conventional/metar_csv2ioda.py
test/testoutput/2020100106_metars_small.nc

This PR updates the metar_csv2ioda.py script to switch from the older string-based ```datetime``` variable to the newer int64-based ```dateTime``` for newer compatibility and overall smaller size IODA files.  Since an internal variable called ```unix_time``` was already present, it was simple to implement and just assign units attribute of ```seconds since 1970-01-01T00:00:00Z```
A separate issue was not created in association with this PR
That it works.
No dependencies
No impacts to other repos.

Switch string datetime to int64 dateTime and reference Epoch (unix_time)

---

CI/buildspec_clang.yml
CI/buildspec_gnu.yml
CI/buildspec_intel.yml

This PR simply adds `site` to CDash so we can create test timing plots for each repo. 
Related to https://github.com/JCSDA-internal/ufo/issues/1328
Test outputs get uploaded to CDash under `CodeBuild` site. 
None
None

Add site to CDash

---

doc/bufr_obs_samples/satwinds_WMO_Insat_sample.txt
doc/bufr_table_samples/satwinds_WMO_Insat_mnemonics.txt
test/CMakeLists.txt
test/testinput/satwind_Insat_wmo.bufr
test/testinput/satwind_Insat_wmoBUFR2ioda.yaml
test/testoutput/satwind_Insat.nc

This PR adds in the capability to run bufr2ioda.x on the WMO-formatted BUFR files that contain either INSAT (India) or the MODIS Aqua/Terra satellite atmospheric motion vectors (AMVs).  The sample input BUFR file contains only INSAT data, but the same yaml was used for a MODIS-only file and works equivalently.  There are only minor differences in the variable list between the 2 different data sets.  This PR includes doc/bufr_table_samples (and obs_samples) with the mnemonics used for the variables.
A separate issue was not created for this.
Working ctest and reviews.
There are no dependencies.
No impacts to other repos expected.

Add converter for SatWinds WMO-formatted BUFR for INSAT and Aqua/Terra

---

test/CMakeLists.txt

This is a follow-up PR to #771 that fixes two additional shell-script based file comparisons.
See #771 and https://github.com/JCSDA-internal/ioda/issues/581 for details.
This PR, together with https://github.com/JCSDA-internal/ioda/pull/595, fixes #771.
All ioda-converters ctests run on macOS
none
none

Second round of "Compatibility with System Integrity Protection on MacOS"

---

tools/ingest/retrieve_data_from_noaa_nomads.sh

Currently the script passes back a non-zero exit from wget if the file does not exist
This happens because there are 4 files names checked for each data type for simplicity though only 2 typically exist.  Rather than explicitly trying to predict the specific 2 names just always check for 4 makes it much simpler
- fixes #1890
Scripts runs and retrieves data
wget

add cleaner exit using curl to check for file on server

---

src/lib-python/ioda_conv_engines.py

The ```lib-python/ioda_conv_engines.py``` contains simple methods to return group names (such as ObsValue, ObsError, etc.) but lacks the method to return the ```MetaData``` group name.  This code addition provides that method.
One was not created (not needed).
Approvals
None
None

Add quick method to return metagroup name

---

CI/buildspec_clang.yml
CI/buildspec_gnu.yml
CI/buildspec_intel.yml

Pass use_eccodes to ecbuild in CI
related to discussion here: https://github.com/JCSDA-internal/ioda-converters/pull/807#issuecomment-1058504726
build ioda-converters with eccodes in CI
None
None

use_eccodes in CI

---

src/marine/20200720.nc

Removed 20200720.nc in folder ioda-bundle/iodaconv/src/marine, this file seems redundant and safe to be removed.
- fixes #828

Remove file 20200720.nc from src/marine

---

src/conventional/metar_csv2ioda.py
test/testoutput/2020100106_metars_small.nc

This PR updates the python code for METAR (csv2ioda) to use new variable names and all conventions.  In addition, a number of improvements were made to make the code more "pythonic" and generic.
Closes #839 
Working ctests including coding_norms and ioda-validate program and positive reviews.
-    [x] To pass the ```ioda-validate``` program, this PR will require the following pull request [IODA 628](https://github.com/JCSDA-internal/ioda/pull/628) be merged due to warnings about global attributes that I added.
This will impact UFO, which will be handled at a later code sprint.

SPRINT: Change METAR converter to align variable names with JEDI naming conventions

---

src/lib-python/ioda_conv_engines.py

This PR adds to `ioda_conv_engines` the capability to check:
- Does the variable MetaData/dateTime exist?
- If so, is it a string?
- If so, convert it to datetime objects
Existing datetime objects are unaffected, and if the variable is defined as a integer with attributes describing the reference time, no changes occur.
- fixes #827 
Approved and tested by folks, note it won't work properly until changes are made to IODA
Needs changes to be made to IODA Python API to handle Python datetime objects before it will write to file properly.
None

Convert ISO date string to Python datetime object

---

src/conventional/amdar_bufr2ioda.py

I encountered a aircraft-AMDAR file that had some data array that was twice as long as all the other arrays.  While it is not optimal, I decided just to chop off the extras.  This could certainly create a problem if the final output list of values does not align with the lat/lon locations properly, but needed a quick fix for right now.
A separate one was not created. Just a quick bugfix here.
This was tested on a real-time file that revealed the problem. No additional test was created.
None
No impacts to other repos expected.

BUGFIX:  Deal with BUFR msg that has more array elements than what was expected (truncate away extras)

---

src/gsi-ncdiag/gsi_ncdiag.py

This PR adds temporary fixes for some issues found with gsi ncdiag conversion of surface pressure observations. 
- add checks for processing GSI obs error and hofx, if the unit is hPa, convert to Pa
- check for large value (~1e9) of surface pressure observation, convert to missing value
N/A 
Test and approve by 2 reviewers.
N/A
N/A

gsi_ncdiag surface pressure converter fixes

---

src/marine/gds2_sst2ioda.py
test/testoutput/gds2_sst_l2p.nc
test/testoutput/gds2_sst_l3u.nc

This PR updates the ```src/marine/gds2_sst2ioda.py``` script to follow the JEDI Data Conventions.  Besides some of the regular changes like ```datetime``` to ```dateTime``` a number of relatively minor improvements to code structure becoming more generic and similar to many other marine converters.
Closes #935 
Success on the 2 ctests of this script (2 different processing levels of input data) and ioda-validate program along with positive reviews.
Waiting on the following PRs:
No impacts if kept within ```feature/sprint-ioda-converters```

Sprint: update src/marine/gds2_sst2ioda.py code for JEDI Data Conventions

---

src/land/smap9km_ssm2ioda.py
test/testoutput/smap9km_ssm.nc

This PR fixes an issue with the variable `vegetaionOpacity` in the smap9k converter. `vegetationOpacity` had a units attribute set to "unitless" which is an outdated setting. Instead the units attribute should be removed (ie, when you have an enumerated/categorical type variable).
None
Ioda converters test for smap9k passes.
The variable `vegetationOpacity` has no units attribute in the smap9k test reference file.
None

Fixed issue in the smap9k converter with the variable vegetationOpacity

---

src/gsi-ncdiag/gsi_ncdiag.py
test/testoutput/sfc_tv_obs_2018041500.nc4

This PR adds a temporary fix for conversion of conv surface t & q, which are 2 meter temperature and moisture observations. In the current conversion, the height of the 2 meter temperature and moisture is computed from the station height of surface pressure plus 2m. Because of this, 2 meter temperature and moisture observations are not properly combined with surface pressure observation. These 2m variables are used in the UFO sfcpcorrected GSI scheme. A temporary fix is to comment out the section that computes the height of 2m variables as station elevation plus 2m, but instead directly use the station elevation for the 2m variables. 
N/A
Tests pass and approval by two reviewers
N/A
N/A

Fix for ncdiag converter for conv surface type

---

src/conventional/synop_bufr2ioda.py

Some BUFR messages in SYNOP data has badly formed strings for siteOrStationName that causes eccodes to throw an exception.  So we need to protect against the key-not-found exception as well as any other exception.
This is a quick bug fix and a separate issue was not created.
Positive review and working ctest.
None
None

Handle other types of Exceptions, some BUFR messages for SYNOP data has badly formed strings

---

src/marine/copernicus_l4adt2ioda.py
test/CMakeLists.txt
test/testinput/dt_global_twosat_phy_l4_20190101_vDT2021.nc
test/testoutput/ioda_dt_global_twosat_phy_l4_20190101_vDT2021.nc

This PR includes the following changes:
1.  replace the keyword 'err' by 'err_sla' in the python script
2. fixed datetime inconsistency. One needs to pass the datetime as an argument in the format: %Y-%m-%dT%H:%M:%SZ
#955

coperl4 bug fix

---

src/compo/mls_o3_nc2ioda.py
src/compo/omi_o3_nc2ioda.py
src/compo/ompsnm_o3_nc2ioda.py
src/lib-python/ioda_conv_engines.py
test/testoutput/mls_o3_l2.nc
test/testoutput/omi_o3_l2.nc
test/testoutput/ompsnm_o3_l2.nc

This PR contains test reference file updates for jcsda-internal/ioda/pull/753. Note that the only thing that has changed are the fill values on the dateTime variables in the new reference files. All other data matches the current files on develop.
related to jcsda-internal/ioda/issues/703
The default fill value for dateTime won't overflow 64-bit integers on all platforms.
None

Update test reference files for the new default fill value for the dateTime variable.

---

src/land/ghcn_snod2ioda.py

This PR fixes an issue that surfaced with the `test_iodaconv_ghcn_snod` test when using a spack-stack build. spack-stack builds the pandas python package using the python installation that is found when spack-stack install is running. The `test_iodaconv_ghcn_snod` test runs a python script `ghch_snod2ioda.py` which uses the pandas read_csv command to read a text file containing station names. The read_csv is called with '\n' as a delimiter, but this was failing on my Mac (and possibly other platforms). This issue is that read_csv with it's built-in parser does not recognize '\n' as a delimiter, so it switches to the 'python' parser which can vary depending on the version that is found when spack-stack runs.
I'm not expert with pandas, so there might be a much better way to solve this. …

Fix for test failure (test_iodaconv_ghcn_snod) with spack-stack build

---

src/bufr/IodaEncoder/IodaDescription.h
src/bufr/IodaEncoder/IodaEncoder.h

This PR syncs up to the ioda engines header file name change in the recent ioda PR merge (jcsda-internal/ioda/pull/764). Sorry about missing this and I appreciate everyone's patience with this issue.
Fixes #1029 
ioda converters successfully builds and all ctests pass.
None
None

Sync up with idoa engines header file name change (Factory.h -> EngineUtils.h)

---

cmake/compiler_flags_Clang_CXX.cmake
cmake/compiler_flags_GNU_CXX.cmake
cmake/compiler_flags_Intel_CXX.cmake
tools/bufr/print_queries.cpp

This PR adds in cmake configuration that adds `-std=gnu++14` to all C++ compile commands. This is done to be consistent with the rest of JEDI, and it enables compiles using Apple-Clang to succeed.
Note this PR is focused on getting the CI build to complete successfully for the `feature/query_cxx` branch (PR #1006). When I tested on my Mac, I got a build of ioda-bundle to complete (using NCEPLIBS-bufr version 11.7.0) but there were 182 ctest failures (of which 3 are expected failures on MacOS). We can address these once we get the build to work (which will likely require the new CI test containers).
None
The C++14 standard is used for all C++ compiles.
None
None

Enable the C++14 standard for C++ compiles.

---

test/CMakeLists.txt
test/testinput/satbias_converter.yaml
test/testinput/satbias_converter_gmi_gpm.yaml
test/testoutput/satbias_gmi_gpm.nc4

Special treatment to those bias correction predictors of GMI_GPM data. These predictors are different from those for other satellite radiance data in GSI.
```
predictors:
- constant
- zenith_angle
- cosine_of_latitude_times_orbit_node
- lapse_rate_order_2
- lapse_rate
- cloud_liquid_water_order_2
- cloud_liquid_water
- emissivity
- scan_angle_order_4
- scan_angle_order_3
- scan_angle_order_2
- scan_angle 
```

Added satbias converter for gmi_gpm.

---

src/gsi-ncdiag/gsi_ncdiag.py

This adds another instrument which can come out of the GEOS-ADAS/GSI called ompslpnc, which is the gmao specific OMPS-LP combined uv/vis retrieval.  This also fixes a bug where layer instruments are output with a specified unit of mol mol-1 vs DU. The unit issue is just a matter of changing the unit attribute for layer sensors. Also a bit of cleanup by splitting the ozone sensors into two groups oz_lay_sensors and oz_lev_sensors to help cleanup some of the code/logic.
None
adds ompslpnc to list of instruments handled by gsi_diags
None
Please list the other repositories (if any) that this PR will require changes in (example below)
None

add ompslpnc for geos adas along with cleanup.

---

src/compo/tropomi_no2_nc2ioda.py

Update the tropomi no2 converter to have two new optional arguments to handle the qa_value flaggin and have a thinning capability give the size and the resolution of the dataset.
The new optional arguments are:
`'-q', '--qa_value'` with the documentation link added for the default value in the description as suggested by @srherbener
`'-n', '--thin'` thinning factor with e.g. 0.9 thinning 90% of the data out. Default is 0.0 and takes all obs. 
CI tests results are not affected.

tropomi better flags handling

---

src/compo/mopitt_co_nc2ioda.py
test/CMakeLists.txt
test/testoutput/mopitt_co.nc

the MOPITT raw files are daily files we need to have additional options to slice the dataset when creating the IODA files for ingest and fit the DA windows (6h).
new option is `'-r', '--date_range'` and is optional. If not specified, the whole dataset in the raw file will be processed.

add capability to create MOPITT IODA files for DA window 

---

src/obserror/obserror2ioda.f90

This PR is adding the option to write `obserror_covariances` into the `obserror2ioda.x` program.
- fixes https://github.com/JCSDA-internal/ioda-converters/issues/1096
The code still works.
None.
None.

Adding the option to write obserror_covariances into obserror2ioda

---

src/gnssro/gnssro_bufr2ioda.py

converter does not use netCDF4 and dependency should be removed
- fixes #1107 
converter behaves as before

remove unused netCDF4 import

---

src/bufr/BufrParser/Exports/Variables/TimeoffsetVariable.cpp

This PR replaces calls to mktime (which assumes local time) with timegm (which assumes UTC). This alleviates the need to force the TZ environment variable to UTC to get the time_t value that is relative to UTC (instead of local time).
None
iodaconv ctests pass
None
None

Use timegm instead of mktime.

---

test/CMakeLists.txt

This PR adds the options to the ioda validator command (in ctests) to ignore warnings and errors. See jcsda-internal/ioda/pull/845 for details.
-fixes jcsda-internal/ioda/issues/843
ctests pass.
None

Add options to validator to ignore warnings and/or ignore errors

---

src/lib-python/orddicts.py

This PR is fixing an import for callable from collections (needed for newer versions of Python, 3.10+).
- fixes https://github.com/JCSDA-internal/ioda-converters/issues/1135
All the CI tests pass.
None.
None.

Fixing import for callable from collections

---

src/goes/goes_converter.py

While creating the Skylab v3.0 files from GOES data, we noticed that PreQC variables are being assigned to floats not ints so this PR fixes the bug.  (Same change was also made into the sprint-ioda-converters feature branch that is pending merge)
Quick bug fix, one was not created.
Turns the float into int.  There was no ctest for this code so it was not exercised.
None
None

Bugfix:  PreQC variables should have ints not floats

---

test/CMakeLists.txt

Fix for issue with airnow test where the python ioda_obs_space package is not found. The fix is to add a PYTHONPATH setting to the test setup.
None
airnow test passes
None
None

Added proper PYTHONPATH setting to the airnow ctest.

---

src/compo/mopitt_co_nc2ioda.py
src/compo/tropomi_no2_co_nc2ioda.py
test/testoutput/mopitt_co.nc
test/testoutput/tropomi_co_total.nc
test/testoutput/tropomi_no2_total.nc
test/testoutput/tropomi_no2_tropo.nc

This makes those two converters actually working and be in phase with what the upgrader is doing.
We have tested various repos and skylab experiments and everything else seems good to go now.
This is the last piece to have everything in place before the merge.
Of course more changes will be done to actually go with the convention as soon as we actually can (i.e. once the IODA Fortran API merged and tested) on the ancilliary variables (averaging kernel and pressure vertices).
For the ObsVal names I think it is better to keep this out as otherwise we would need to re-upgrade all testinput/output/yaml data in ufo/ufo-data/fv3-jedi/fv3-jedi-data and r2d2 for slylab...
Thanks for your understanding on this!

make L2 trace gas converters work and be consistent with what the upgrader

---

src/compo/mopitt_co_nc2ioda.py
src/compo/tropomi_no2_co_nc2ioda.py
test/CMakeLists.txt
test/testoutput/mopitt_co.nc
test/testoutput/tropomi_co_total.nc
test/testoutput/tropomi_no2_total.nc
test/testoutput/tropomi_no2_tropo.nc

changes for L2 trace gas varnames to follow conventions

changes for L2 trace gas varnames to follow conventions

---

src/conventional/sonde_tac2ioda.py
test/testoutput/2021081612_sonde_small.nc

A bug existed for converting legacy/text (TAC) radiosonde reports with respect to how winds are sometimes in knots versus meters per second.  WMO manual on codes (chain of pages 85, 203, 211, 254) says that day of month is incremented by 50 when winds are reported in knots versus m/s.  So a new global variable `scale_wspd` was added to signify a units conversion is needed.
A separate one was not created.
Working ctests and approval.  I checked many sites in USA vs. Europe to see that BUFR sondes and text sondes give the same results for wind speeds.
None
None expected.

Radiosonde legacy/text (TAC) bugfix for knots vs m/s based on day-of-month coding per WMO manual on codes

---

src/conventional/sonde_bufr2ioda.py
test/testoutput/wmo_raob_double.nc4

BUFR radiosonde files (picked up with LDM in real-time) often contain duplicates - sometimes as many as three duplicates of the first message, more often only one dupe.  This PR causes the converter to capture which stations are found and skip past any subsequent soundings from the same site.  For a real-time example file, the output file size was decreased by 2/3rds when doing the skipping.
A separate one was not created.
Positive reviews and working ctests.
None
None

Radiosondes: BUFR incoming data (from LDM), skip duplicates

---

src/conventional/sonde_bufr2ioda.py
src/conventional/sonde_tac2ioda.py
src/lib-python/meteo_sounding_utils.py
test/testoutput/2021081612_sonde_small.nc
test/testoutput/wmo_raob_double.nc4

When running an entire month of files through the radiosonde converters (BUFR and TAC input), they would sometimes crash.  So this PR is bug fixing.  Also, since the saturation water vapor pressure code is unreliable at super low temperatures (less than about -78C), the specificHumidity variable is limited to when dewpointTemperature is greater than -77C as a precaution.
A separate one was not created.
Approvals. The existing test data did not contain the kind of data that caused failure so no pre-existing ctest found the error.
None
None expected.

Bugfix:  found times when converters crashed when testing with dozens of input files

---

src/conventional/amv_ssec_ascii2ioda.py
test/testoutput/satwinds_ssec2021080103.nc

The text data downloaded from SSEC uses positive longitudes for western hemisphere and negative longitudes for eastern hemisphere.  This PR fixes to world convention using a -1.0 multiplier for their longitudes.
Rapid bug fix, a separate issue was not created.
It will be nice to see the change on experiments.jcsda.org but this was discovered by looking at experiment id=`369c00` that clearly shows the error.
None
None

BUGFIX: incoming SSEC AMV data has wrong convention for east/western hemispheres

---

doc/bufr_table_samples/mesonet.nc255001.bufr.table.txt
doc/bufr_table_samples/mesonet.nc255101.bufr.table.txt
doc/bufr_table_samples/mesonet.nc255102.bufr.table.txt
doc/bufr_table_samples/mesonet.nc255111.bufr.table.txt
doc/bufr_table_samples/mesonet.nc255131.bufr.table.txt
doc/bufr_table_samples/mesonet.nc255161.bufr.table.txt

This PR provides BUFR tables for each Mesonet data subset, which are described below:
- NC255001 --> MTYP 255-001  Mesonet from MADIS: Denver Urban Drainage  
- NC255002 --> MTYP 255-002  Mesonet from MADIS: RAWS (NIFC)            
- NC255003 --> MTYP 255-003  Mesonet from MADIS: MesoWest (many subpr)  
- NC255004 --> MTYP 255-004  Mesonet from MADIS: APRS WeatherNet        
- NC255005 --> MTYP 255-005  Mesonet from MADIS: Kansas DOT             
- NC255006 --> MTYP 255-006  Mesonet from MADIS: Florida                
- NC255007 --> MTYP 255-007  Mesonet from MADIS: Iowa DOT               
- NC255008 --> MTYP 255-008  Mesonet from MADIS: Minnesota DOT          
- NC255009 --> MTYP 255-009  Mesonet from MADIS: Anything Weather       
- NC255010 --> MTYP 255-010  Mesonet from MADIS: NOS …

[3D]RTMA Mesonet BUFR tables

---

test/CMakeLists.txt
test/testinput/bufr_ncep_adpupa.yaml

There was no ctest in ioda-converets for the existing ADPUPA BUFR YAML, bufr_ncep_adpupa.yaml. This PR adds a new ctest, test_iodaconv_bufr_ncep_adpupa2ioda, for this YAML. 
- fixes #1183 
The ctest should pass.
merge #1174  first
None

Ctest for the existing bufr_ncep_adpupa.yaml

---

src/compo/viirs_aod2ioda.py
test/testoutput/viirs_aod.nc

This PR fixed the VIIRS AOD obs error estimation based on retrieval surface (QCPath) in viirs_aod2ioda.py
The QCPath are 8-bit integers and should be interpreted bit by bit. Briefly, if the right most bit equals 1, the data is retrieved from water; if the second right most position equals 1, the data is retrieved from bright land; otherwise (both equal 0), it is from dark land.
- Correct obs error estimation based on surface type in viirs_aod2ioda.py ##<[1201](https://github.com/JCSDA-internal/ioda-converters/issues/1201)>
Good reviews.
None.
None.

Fix retrieval surface and obs error in viirs_aod2ioda.py

---

src/goes/goes_converter.py

As discussed in #1204 the GOES converter was creating the wrong solar angles (zenith and azimuth).  The new code is producing the correct angles.
The new code does not follow this reference [https://gist.github.com/anttilipp/1c482c8cc529918b7b973339f8c28895](https://gist.github.com/anttilipp/1c482c8cc529918b7b973339f8c28895), but the results of the new code are a match (and simpler/shorter).
- fixes #1204 
Correct angles and positive reviews.  FYI: this converter has never had a `ctest` because the input files are super large.
None
No impacts to other repos.

Bugfix:  solar zenith/azimuth angles were not computed correctly, new code fixes it.

---

test/testinput/bufr_ncep_highRes_sonde.yaml
test/testoutput/gdas.t12z.adpupa_bufr_nc002103.tm00.nc

This PR adds the longitude/latitude displacement and WIGOSID to the existing high-resolution radiosonde YAML, which is required by both global and regional users, and also replaces dewpointTemperature with dewPointTemperature.
This PR partially addresses the following issue #1184. 
Good reviews and pass the ctest.
None
None

Longitude/latitude displacement addition to the high-resolution radiosonde YAML

---

CMakeLists.txt

This PR will install the python package pyiodaconv in /lib/python{VERSION}/pyiodaconv instead of /lib/pyiodaconv. Doing t
This is reduces settting PYTHON_PATH by one directory and eventually will make skylab as a whole easier to use.
- fixes #1211
Python components are installed correctly without ctests failing for ioda-converters and any downstream packages.
None

Install pyiodaconv according to python conventions

---

src/gsi_ncdiag/gsi_ncdiag.py
test/testoutput/satwind_obs_2018041500.nc4
test/testoutput/sfc_tv_obs_2018041500.nc4

Save GsiInputObsError, GsiAdjustObsError,ObsSubType, Dupobs_Factor, and dup_kx_vector which contains ObsType (kx) numbers for duplicated observations.  These values are used in GMAO's JEDI/UFO configurations and tests.

Save observational errors, subtype, duplicate factor from GEOS tests.

---

tools/ingest/retrieve_data_from_noaa_nomads.sh

instead of repeating the hour add year month and day to filenames
- fixes #1224 
script downloads nomads files from NOAA public server

add more time information to the file names

---

tools/ingest/retrieve_from_nasa.sh

following guidance from NASA update GPM-GMI data pull to level 1CR
- fixes #1227 
script pulls data from NASA public server

update GMI pull from L1B to L1CR

---

CMakeLists.txt
cmake/compiler_flags_Clang_CXX.cmake
cmake/compiler_flags_GNU_CXX.cmake
cmake/compiler_flags_Intel_CXX.cmake
src/bufr/CMakeLists.txt

This PR contains cmake configuration changes that explicitly specify using the C++14 standard for C++ compiler calls. This is being done to fix issues with Mac builds where, in some cases, the C++11 standard was being used.
None
The feature/query_python branch compiles successfully on the Mac.
None
None

Specify C++14 standard for C++ compiles

---

src/bufr/BufrParser/Exports/Variables/TimeoffsetVariable.cpp
test/CMakeLists.txt
test/testinput/bufr_ncep_prepbufr_adpupa.yaml
test/testoutput/bufr_ncep_prepbufr_adpupa.nc

TimeoffsetVariable did not set group_by fields correctly in the Query Info objects it returned to identify the queries it needs. This PR fixes that.
#1128 
New unit test test_iodaconv_bufr_ncep_prepbufr_adpupa passes.

Fix for group_by bug in timeoffset variable.

---

test/CMakeLists.txt
test/testinput/bufr_ncep_rtma_mesonet.yaml
test/testinput/rtma_ru.t00z.msonet.tm00.bufr_d
test/testoutput/rtma_ru.t00z.msonet.tm00.nc

This PR adds an ioda-converters for the [3D]RTMA mesonet data using the following three files: 
- testinput/bufr_ncep_rtma_mesonet.yaml
- testinput/rtma_ru.t00z.msonet.tm00.bufr_d
- testoutput/rtma_ru.t00z.msonet.tm00.nc
This YAML will serve for the following mesonet subsets: 
255001 255002 255003 255004 255005 255006 255007 255008 255009 255010 255011 255012 255014 255015 255016 255017 255018 255019 255020 255021 255022 255023 255024 255025 255026 255027 255028 255029 255030 255031 255101
- #1132
- #1191
- 
- Good reviews
- Validation of the output results, which are performed in #1191 
- _ioda-validate.x_, the following results were obtained using ObsSpace.ymal from #https://github.com/JCSDA-internal/ioda/pull/986
Final results:
errors:      0 …

Ioda-converters for the rtma mesonet data 

---

test/testinput/bufr_query_python_to_ioda_test.py
test/testoutput/bufr_query_python_to_ioda_test.nc

This pull request improves an testinput BUFR python example that writes data into an IODA Netcdf4 file. It turns out that if you don't set the parameter on each variable it (ioda) will pick **0** to represent the fill_value (treated as missing value by Netcdf). 
**Note**: this pull request only affects an example test file and associated output data.
https://github.com/JCSDA-internal/ioda/issues/989

Improved BUFR python example (IODA vars need params)

---

src/bufr/BufrParser/Query/ResultSet.cpp
src/bufr/BufrParser/Query/ResultSet.h
test/CMakeLists.txt
test/testinput/bufr_query_fieldname_validation.py

Python interface would crash the interpreter if ResultSet::get was given an invalid field name. This PR adds exceptions to prevent this and gives the user more useful feedback.
#1248 
New test **test_iodaconv_bufr_query_fieldname_validation** passes.

Validate field names in ResultSet::get

---

src/bufr/BufrParser/Query/ResultSet.cpp
src/bufr/BufrParser/Query/ResultSet.h
src/bufr/BufrParser/Query/python_bindings.cpp
test/testinput/bufr_query_python_test.py

Make it possible to do type override when doing resultSet get in python code. Example:
```python
q = bufr.QuerySet()
q.add('day', '*/DAYS')
q.add('longitude', '*/CLAT')
with bufr.File(DATA_PATH) as f:
r = f.execute(q)
day_float = r.get('day', type='float')
```
#1251

Extended code to expose type override for query python.

---

test/testinput/bufr_ncep_ssmis.yaml

add an updated yaml for the NCEP BUFRlib SSMIS file
- fixes #1244 
running with these file in UFO depends on https://github.com/JCSDA-internal/ufo/pull/2835
IODA output created and ctest passes

add updated SSMIS file for bufr2ioda for NCEPBufrLib

---

test/testinput/prepbufr_adpsfc_api.py

Proposed changes to generalize the new NCEP PREPBUFR ADPSFC to IODA converter so that input and output files as well as the date can be passed from the command line
Resolves #1299 
none
none

Generalize prepbufr adpsfc converter

---

test/CMakeLists.txt
test/testinput/mopitt_co.he5

Adding back in mopitt_co.he5. This was taken out due to the git-lfs problem with this file.

adding back in mopitt_co test and file

---

test/CMakeLists.txt
test/testinput/bufr_ncep_rtma_adpsfc.yaml
test/testinput/rtma_ru.t0000z.adpsfc_nc000101.tm00.bufr_d
test/testoutput/rtma_ru.t0000z.adpsfc_nc000101.tm00.nc

This PR adds an ioda-converters for the [3D]-RTMA adpsfc data using the following three files:
- testinput/bufr_ncep_rtma_adpsfc.yaml
- testinput/rtma_ru.t0000z.adpsfc_nc000101.tm00.bufr_d
- testoutput/rtma_ru.t0000z.adpsfc_nc000101.tm00.nc
- Resolves #1314 #1315 #1318 
- Good reviews
- Validation of the output results, which are performed in #1318 
- ioda-validate.x, the following results were obtained using ObsSpace.ymal from #1315 
**Final results:**
_errors:      0
warnings:    0_
- There are no dependencies.
- None

Ioda-converters for the [3D]-RTMA ADPSFC data

---

src/compo/viirs_aod2ioda.py
test/testoutput/viirs_aod.nc

In the the VIIRS AOD Level 2 data file, QCPath is set with a valid range of 0-31. The values out of 0-31 are not read in properly by the converters, so that the retrieval surface is not correctly identified. This PR is to fix this minor bug in reading QCPath, so that values out of 0-31 are valid. 
- None.

bug fix to make QCPath values out of 0 to 31 valid

---

test/CMakeLists.txt
tools/iodaconv_comp.sh

This PR is adjusting the verbosity flag check inside `tools/iodaconv_comp.sh`. This allows the user to pass specific flags: `[y,t,yes,true]` (regardless of its case variations). Some clean-up adjusting indentation inside `test/CMakeLists.txt` to make it consistent throughout the file has been performed as well.
Resolves TO-BE-CREATED
None.
None.

Adusting the verbosite flag check used by `tools/iodaconv_comp.sh`

---

src/compo/tempo_nc2ioda.py

In the proxy data there are a lot of inconsistencies in how the mask is specified from a file to another.
The changes allow the converter to run on proxy files and produce ioda files for our tests period.
None
None
- [ x] I have performed a self-review of my own code
- [ x] I have run the unit tests before creating the PR

bug fixes for the tempo converter

---

src/gsi_ncdiag/combine_obsspace.py

The `combine_obsspace` code for contains a nasty bottle neck when combining GeoVaLs, where there is a rather inefficient nested loop. For GMAO when converting all the of the observations from GSI to IODA format and including the GeoVaLs it was taking around 50 minutes. After this change it's more like 8 minutes.

Refactor the bottle neck in combining the geovals

---

src/gsi_ncdiag/gsi_ncdiag.py

It has become clear that for folks interested in replicating the GSI, and thus users of gsi_ncdiag.py, it would not be possible to handle Pibal and Sonde winds using the same observation operator in UFO. This PR makes it such that the converters will output a separate pibal file and no longer include kx=221 in the sondes file.
N/A
N/A
N/A

Split Pibal from Sondes

---

src/gsi_varbc/GsiAircraftBiasConverter.cc
test/testoutput/varbc/acft_out.nc4

This adds lastUpdateTime as an int64 seconds since 1970 that IODA can decipher (hopefully!)
Resolves #<issue_number>
Expected impact on downstream repositories:

Add lastUpdateTime to aircraft VarBC files

---

test/CMakeLists.txt
test/testinput/TROPICS01.L1B.V03-04.ST20220216-012443.ET20220216-025955.nc
test/testinput/tropics_2022021600.nc
test/testoutput/20220216T00Z_PT3H_tms_tropics-01.nc4

A new `ufo ctest` was made for `tropics`, but the `geovals` file needed for that test was too large. The raw data was reduced and converted and then run in `skylab` to generate smaller geovals files. In order to keep the workflow consistent using the `ioda ctest` `testoutput` file as the `testinput` file for the `ufo ctest`, the `ioda-converter` test files needed to be replaced.
The `iodaconv ctest` passes with the new files, by running `ctest -R test_iodaconv_tropics -VV` in the `build` directory. 
Resolves #<issue_number>

replacing tropics ctest files with smaller data case

---

CMakeLists.txt

Set options to find framework (macOS) and registry (Windows) Python after regular (aka "Linux-style") Python installations.
I tested this together with https://github.com/JCSDA-internal/ioda/pull/1122 on my macOS and it did find the spack-stack Python installation first.
Working towards https://github.com/JCSDA-internal/jedi-docs/issues/656
Merge together with https://github.com/JCSDA-internal/ioda/pull/1122 and https://github.com/JCSDA-internal/jedi-docs/pull/665 (although not strictly required)
n/a

Add aids to find correct Python3 (find framework/registry last)

---

src/gnssro/gnssro_bufr2ioda.py

Adds the option to save LSW from CDAAC processed bufr files as its own variable when a flag is set.
Resolves #1393 
none
none

Add option to save LSW in gnssro bufr2ioda

---

src/obserror/obserror2ioda.f90

This PR fixes intermittent failures of the ctest `test_iodaconv_obserror`. The issue was an integer variable being used for the file unit number which was uninitialized when used in a file open statement.
None
None
Expected impact on downstream repositories:
None

Fixed fault with unintialized file unit variable.

---

test/CMakeLists.txt

This PR changes the tolerance value for comparing floating point numbers to a consistent, non-zero value. This is coded in a single variable, IODA_CONV_COMP_TOL, and used everywhere the iodaconv_comp.sh script is used. Currently IODA_CONV_COMP_TOL is set to 1.0e-3 (relative tolerance of 0.001 percent).
Partially addresses #1378
None
Expected impact on downstream repositories:
None - no functional changes

Set a consistent, non-zero tolerance for comparing floating point values

---

src/satbias/SatBiasConverter.cpp

OOPS missingValue was changed, and thus broke ioda-converters. This PR should fix that.
Resolves #1403 1403

Change missing value in satbias converter

---

cmake/compiler_flags_GNU_Fortran.cmake

The compiler flags for linux need to be fixed for linux due to recent change in code. 
https://github.com/JCSDA-internal/ioda-converters/pull/1399
We should no longer need mcmodel and thus can delete it.
Resolves #1398 
None

fix for compiler flags
