JCSDA-internal/ioda-converters

- src/bufr2nc.py
- src/gpsbufr2nc.py
and include a gpsro bufr test file
> add utility for converting gpsro bufr file to netcdf

- src/bufr2ncObsTypes.py
Changes for separating out the two replication tests.
> Csd develop

- src/bufr2ncObsTypes.py
Added calculation of latitude and longitude.
Added calculation of time since the epoch to be used with Locations object in UFO
> Switched to using netcdf CF names in output netcdf files.

- src/bufr2ncObsTypes.py
> Revert "Switched to using netcdf CF names in output netcdf files."

- src/met-office/odbapi2nc.py
This pull request contains 3 modifications:
1. it converts the relative humidity obs. variable in the ODB API file to specific humidity where possible. It is understood that this is not the correct place to convert variables like this, but it is being done to facilitate the short-term goal of performing DA on the Met Office data as soon as possible. This code should be removed in the future.
2. We found that the data files sometimes have multiple rows for the same 'varno' and location. This doesn't fit with the 'LocationKey' concept we use to store the data in the python dictionary tree. We don't know why this is, but sometimes the last row for a 'varno' contains a NULL for the obsvalue, and the NULL would overwrite the obsvalue contained in an earlier row in the dictionary tree. So the …
> Convert humidity variable. Change qcVal. Ignore NULL values.

- src/lib-python/ioda_conv_ncio.py
default missing value was 0, changed to the netcdf default missing values
> missing values set to netcdf default missing  values

- src/lib-python/ioda_conv_ncio.py
separate string lengths for datetime and variable names
> separate string lengths for datetime and variable names

- src/marine/CMakeLists.txt
- src/marine/hgodas/CMakeLists.txt
- src/marine/hgodas/hgodas-adt2ioda.py
- src/marine/hgodas/hgodas-insitu2ioda.py
- src/marine/hgodas/hgodas-sst2ioda.py
converters for Hybrid-GODAS formatted SST / ADT / insitu TS
closes #89
> converters for Hybrid-GODAS formatted SST / ADT / insitu TS

- src/marine/hgodas/hgodas-adt2ioda.py
- src/marine/hgodas/hgodas-insitu2ioda.py
- src/marine/hgodas/hgodas-sst2ioda.py
fixed hours in input date of hgodas converter
> fix bug with hours in date

- src/marine/CMakeLists.txt
- src/marine/gmao/CMakeLists.txt
- src/marine/gmao/gmaoobs2ioda.py
Add IODA converter for GMAO ocean observations.
Change-Id: If5fb67f50a0af90627549d1acf2b606a4bf32c34
> add GMAO ocean obs. converter

- src/marine/CMakeLists.txt
- src/marine/nesdis/CMakeLists.txt
- src/marine/nesdis/nesdis_sst2ioda.py
nesdis SST files.
tested with AVHRR/VIIRS L3U/L2P
> nesdis sst converter added

- src/marine/CMakeLists.txt
- src/marine/emcice/CMakeLists.txt
- src/marine/emcice/emcice2ioda.py
Converts l2 ice fraction to ioda
> EMC ice fraction converter

- src/marine/smap/sss2ioda.py
file rewritten to handle both JPL and RSS formats of SSS files.
numpy masking is done to remove missing values.
**temporary**:  all obs with bad qc flags removed, for now, until preqc obsfilter can be made working for SSS
>  SMAP conversion files now handles RSS and JPL types

- src/marine/CMakeLists.txt
- src/marine/gds2/CMakeLists.txt
- src/marine/gds2/gds2_sst2ioda.py
- src/marine/nesdis/nesdis_sst2ioda.py
the nesdis sst ioda converter was generalized to handle any* GDS2.0 formatted SST file.
Optional thinning was also added.
> gds2.0 SST files

- src/marine/CMakeLists.txt
> Moving emcice2ioda to bin during ecbuild

- src/marine/emcice/emcice2ioda.py
Added thinning to emc ice fraction.
> Thinning of emc ice fraction

- src/gsi-ncdiag/combine_conv.py.in
Change-Id: Id204e317b16e456dd209369aac2c56ab75050607
> make combine_conv.py compatible with bin/lib structure

- test/testinput/smap_sss_rss.nc
Reverts JCSDA/ioda-converters#192
> Revert "bugfix/smap-sss-int-fails"

- test/testinput/smap_sss_rss.nc
Reverts JCSDA/ioda-converters#193
> Revert "Revert "bugfix/smap-sss-int-fails""

- src/gsi-ncdiag/gsi_ncdiag.py
- src/lib-python/ioda_conv_ncio.py
- test/testoutput/amsua_aqua_obs_2018041500.nc4
Added in "TestReference" type to GSI ncdiag for comparison of GSI computations to UFO computations
> GSI @TestReference capability

- src/gsi-ncdiag/gsi_ncdiag.py
Replace vertical_velocity with the new name "upward_air_velocity".
> Fixed veritical velocity name to upward_air_velocity

- src/marine/CMakeLists.txt
- src/marine/argoClim2ioda.py.in
- test/CMakeLists.txt
- test/testinput/argoclim_test.nc
- test/testoutput/argoclim.nc
This PR adds a marine converter; specifically it converts the Argo climatology (global 1 degree x 1 degree) dataset produced by OI into IODA format.
This dataset can be useful for validation purposes while performing marine DA.
A test and test files (sampled down to 3 vertical levels and 4x4 box in the equatorial Pacific).
@srherbener I would like to draw your attention to the code block on L128 which contains 4(!) for loops and is extremely slow.  This is required to generate the `locKey` on L134.  Do you think there can be a way to speed this up?  I don't doubt one has to look over all time and horizontal points, but the vertical profile could be constructed differently (optimally?).  Or should we just ignore the slowness for the time being?
> ARGO Climatology converter.

- src/marine/emc_ice2ioda.py.in
Closes #222 
1. The PR addresses the issues with the current emc_ice observation format. 
2. And two typos causing runtime errors.
> Bugfix/emc ice 

- src/marine/gmao_obs2ioda.py.in
Remove observations from the GMAO S2S system that are far from the expected value.
This could be done in the QC filter as well, but then one would have to remember to implement that everytime.  This way, the QC is done before we even get to assimilating these bad obs.
Change-Id: I3abbfd790440db559e1677779eaa6fbc1175d197
> QC GMAO obs.

- buildspec_clang.yml
- buildspec_gnu.yml
- buildspec_intel.yml
- src/odc/nc2odb.py
- test/testoutput/gnssro_obs_2018041500_s.odb
- test/testoutput/sondes_obs_2018041500_m.odb
Initially, this PR is here just to debug the CodeBuild test failures. If it turns out that a code change to nc2odb.py is necessary, then this will provide those changes.
> Fix CodeBuild test failures

- buildspec_clang.yml
- buildspec_gnu.yml
- buildspec_intel.yml
This PR fixes the issue with triggering CodeBuild only when a PR is created or changed or merged.
I need to make changes on AWS side right after this PR is merged.
> codebuild branch name

- src/gsi-ncdiag/gsi_ncdiag.py
change variable name in geoval from mole_fraction to mass_mixing_ratio and in ioda obs data files, the variable name is changed from mole_fraction_of_ozone to integrated_layer_ozone and the unit from 1 to DU
> branch feature/hliu_O3: change variable name and unit

- src/lib-python/CMakeLists.txt
- src/lib-python/meteo_utils.py
A set of functions that may assist others in creating new variables from other ones when preparing IODA-ready data/files. Where possible, attribution to the source of the function is provided in comments.  If needed by specific centers/users, we can create a series of functions that may have alternative forms of higher or lower accuracy.  A good example is found in the function called "e_sub_s" that computes saturation vapor pressure or liquid (another function for ice) and there are 2 alternatives in comments to permit other relationships.  In that case, perhaps a form of Case/Switch block code construct can provide access to alternates.
> set of functions for common meteorological utilities for creators of IODA-ready data files

- src/gsi-ncdiag/CMakeLists.txt
Add the combine_conv to lib-python so it can be called from another Python routine
> Add the combine_conv to lib-python ... 

- buildspec_clang.yml
- buildspec_gnu.yml
- buildspec_intel.yml
This PR changes CI to clone from jcsda-internal.
- fixes #355
> switch to jcsda-internal

- src/satbias/README.md
Adds documentation for satbias2ioda converter in the `README.md`.
- fixes https://github.com/jcsda-internal/ioda-converters/issues/417
> add readme for satbias converter

- test/CMakeLists.txt
- test/testinput/bufr_satwnd_new_format.bufr
- test/testinput/bufr_satwnd_new_format.yaml
- test/testinput/bufr_satwnd_old_format.bufr
- test/testinput/bufr_satwnd_old_format.yaml
- test/testoutput/NC005031.nc
- test/testoutput/NC005066.nc
- tools/run_satwnds/run_satwnds.py
- tools/run_satwnds/satwnds_new_subset_template.yaml
Branch: [/feature/iodaconv_GNAPS](https://github.com/JCSDA-internal/ioda-converters/tree/feature/iodaconv_GNAPS)
Issue: #461 
https://github.com/JCSDA-internal/ioda-converters/issues/461
This PR means to add mnemonic GNAPS to satwnds_new_subset_template.yaml for improved ioda-converters robustness. 
This PR will close issue #461
> Added GNAPS mnemonic to satwnds_new_subset_template.yaml

- src/gsi-ncdiag/gsi_ncdiag.py
Add AMSR2 to list of radiances in GSI diag converter
> Add AMSR2 to list of radiances in GSI diag converter

- src/marine/smap_sss2ioda.py
- src/marine/smos_sss2ioda.py
This PR fixes the bug reported in #493 
The SMAP SSS converter works for JPL h5 and RSS nc L2 SSS feeds.
Also updates the smos_sss2ioda.py with @SCRIPT_LIB_PATH@ version
[See the JEDI Documentation](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/pullrequest.html) for further information.
- fixes #<493>
> Fixed bug: SMAP JPL 

- src/marine/viirs_modis_l2_oc2ioda.py
- test/CMakeLists.txt
- test/testoutput/modis_aqua_oc_l2.nc
- test/testoutput/viirs_jpss1_oc_l2.nc
> upgrade viirs_modis_l2_oc to use iodav2

- src/gnssro/gnssro_bufr2ioda.py
When using raw GNSS-RO observations particularly in a near real-time feed occultation profiles deemed non-nominal are generally removed.  
Successful run through UFO comparing number of occultations from this pathway with that from an alternate feed where non-nominal profiles have been removed.
>  add non-nominal check for processing near real time files

- src/conventional/decode_bufr_LDM_raob.py
The conversion of BUFR raob with the python converter needed some additional error handling
- fixes #1892
Successful conversion of BUFR raob to IODA netCDF4 file
ecCodes
>      add some additional error handling for BUFR decode or raob

- src/conventional/amv_ssec_ascii2ioda.py
- test/testoutput/satwinds_ssec2021080103.nc
corrected day and month being read in from file
- fixes #<issue_number>
bug is fixed and month and day are correct for 2 digit month and day
> fixed incorrect reading of day and month

- src/land/smap9km_ssm2ioda.py
- test/testoutput/smap9km_ssm.nc
Based on the request from the users from Land DA, I added two variables: easeRowIndex and easeColumnIndex. At the same time, the converter dependency on input filename issue is fixed.
- fixes #808 
ctest passed, testoutput was updated, and the PR is reviewed and merged into develop
No
Please list the other repositories (if any) that this PR will require changes in (example below)
No
> Update 9 km SMAP soil moisture converter 

- src/conventional/amv_ssec_ascii2ioda.py
- test/testoutput/satwinds_ssec2021080103.nc
for the ioda-converter SPRINT branch
correct the extraction of the date and time from the SSEC ascii geostationary satellite winds
- fixes #925 
successful conversion of data and testing through UFO
> Bugfix/ascii satwind datetime fix for SPRINT

- src/conventional/amv_ssec_ascii2ioda.py
The python script src/convential/amv_ssec_ascii2ioda.py was incredibly slow when reading multiple files. This change improved performance a factor of 5 on our test by creating a local_data for each file then appending that to the global data variable rather than appending to global_data directly. Since np.append reallocates an array with each append this saves memory from thrashing. A read of six files went down from 6min to 65 seconds. Only the file in question was changed.
The above issue was outlined in issue #933
The changes are done and ready to be merged after review. The time is nearly linear with # of files accounting for file sizes.
None 
None. No changes in interfaces from develop.
> fix for performance bug in sat winds 

- src/compo/viirs_aod2ioda.py
Issue 931 requested that arg list in viirs_od2ioda.py to be changed to all required. This PR makes those changes.
- fixes #931
PR is approved and merged. 
None
> Change optional arguments in viirs_aod2ioda.py to  be required.

- doc/bufr_obs_samples/sonde_bufr_sample.txt
- doc/bufr_table_samples/satellite_IASI_mnemonics.txt
- doc/bufr_table_samples/sonde_bufr_mnemonics.txt
During feature/sprint-ioda-converters, @gthompsnJCSDA added a lot of files to document BUFR into the doc/bufr_table_samples and doc/bufr_obs_samples.
These are good files for everyone to have, and it's a shame to have them in a limbo feature branch for longer. So, let's merge them to develop.
> Add new mnemonics and sample files

- src/marine/godae_profile2ioda.py
This PR tests a PreQC filter added to conversion scripts for fnmoc profile data through a ctest.
- fixes #981 
ctest pass with a few sec
> PreQC filter for FNMOC profile data

- tools/ingest/retrieve_data_from_noaa_nomads.sh
the GNSS-RO data from NOAA changes locations update in ingest script to add new location
- fixes #1008 
script allow pull of specifically GNSS-RO data but other data can be pulled as well
>  update the web address to do the pulls from NOAA

- src/marine/rads_adt2ioda.py
- test/testoutput/rads_adt.nc
This PR tests updated conversion scripts for rads adt through a ctest.
- fixes #989 
Pass the ctest
> ADT data conversion script associated with egm2008 gravity model

- CI/CMakeLists.txt
- CI/buildspec_clang.yml
- CI/buildspec_gnu.yml
- CI/buildspec_intel.yml
*(Instructions: replace text in this and all sections with your own text)*
Provide a detailed description of what this PR does.
What problem does it fix? What new capability does it add?
[See the JEDI Documentation](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/pullrequest.html) for further information.
- fixes #<issue_number>
If this does not close an existing issue, then [be sure to add a Pipeline, Label, Estimate, Assignees, and Epic](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/practices/issues.html)
What does it mean for this PR to be finished?
If there are PRs that need to be merged before or along with this one, please add …
> changes needed for new containers

- CI/buildspec_intel.yml
This PR fixes a bug in CodeBuild Intel yaml.
> bugfix in CI

- src/goes/goes.py
- src/goes/goes_converter.py
- src/goes/goes_util.py
- src/goes/test_goes_converter.py
Update the GOES converter (python) to retrieve variables in MetaData that come from internal file (global) attributes or variables to make it more generalized.  Other areas of improvements are listed in the linked issue.
- closes #1105 
At least 2 positive reviews.  I am considering the creation of a tier 2 or tier 3 test being added since this code has only been tested in CI for coding standards, not the results of operation/usage.
There should be none
There should be no impacts to other repos.
> Modernize the GOES converter (python) to prepare for more widespread usage in JEDI

- src/compo/modis_aod2ioda.py
- src/compo/viirs_aod2ioda.py
- test/testoutput/modis_aod.nc
- test/testoutput/viirs_aod.nc
- Make sure the converter are producing the correct obs format to be handled correctly by ioda and oops. 
- Removing non-pythonic for loops, which speeds up the converters, relevant for viirs @CoryMartin-NOAA.
- fixes partially https://github.com/JCSDA-internal/jedi-bundle/issues/29
> Fix AOD converters

- src/gsi_ncdiag/combine_files.py
- src/gsi_ncdiag/combine_obsspace.py
- src/gsi_ncdiag/gsi_ncdiag.py
Updated gsi_ncdiag.py for GPSOR data.
Removed lib_python from combine_files.py and combine_obsspace.py.
> Updated gsi_ncdiag.py for GPSRO data

- tools/ingest/retrieve_data_from_noaa_nomads.sh
update script which pull BUFR files from NOAA NOMADS server
- fixes #1214 
can pull NOMADS data
> update NOMADS data pull

- tools/ingest/retrieve_from_nasa.sh
add more NASA mission support
- fixes #1222 
people agree it is useful for a time before full ewok integration
> additional NASA mission ingest script

- src/goes/goes_converter.py
- src/goes/goes_latlon.py
Full description found in #1229.
In addition, the sensorViewAngle was an identical duplicate of sensorZenithAngle, so I removed this variable.
Closes #1229 
Review approvals
None
No impact to other repos expected.
> Bug fix for GOES sensorAzimuthAngle

- src/compo/mopitt_co_nc2ioda.py
- src/compo/tropomi_no2_co_nc2ioda.py
- test/testoutput/mopitt_co.nc
- test/testoutput/tropomi_co_total.nc
- test/testoutput/tropomi_no2_total.nc
- test/testoutput/tropomi_no2_tropo.nc
This is part of the effort of having 2d structures for ancillary data such a pressure vertices and averging kernel functions.
This makes the data set much more readable.  
https://github.com/JCSDA-internal/ioda-converters/issues/908
https://github.com/JCSDA-internal/ufo/issues/2781
merged in develop
none
> 2d arrays in trace gas converters 

- src/hdf5/atms_netcdf_hdf5_2ioda.py
these changes are needed to decode the split SDR and GEO files from NOAA CalVal team
- fixes #1240 
converter creates IODA files usable by JEDI
> add some changes needed to decode split SDR GEO h5 files

- cmake/compiler_flags_Cray_Fortran.cmake
- cmake/compiler_flags_GNU_Fortran.cmake
- cmake/compiler_flags_Intel_Fortran.cmake
- cmake/iodaconv_compiler_flags.cmake
update compiler flags keeping in sync with IODA
- fixes #1242
> update cmake flags and add one for Cray FORTRAN

- test/testinput/bufr_ncep_ssmis.yaml
Provide a detailed description of what this PR does. What problem does it fix? What new capability does it add?
Resolves #<issue_number>
Expected impact on downstream repositories:
> Light version

- test/testinput/bufr_ncep_prepbufr_adpupa.py
Generalize the prepbufr adpupa converter to allow input, output, and date to be passed. Leave the test file as the default 
Resolves #1317 
none
none
> Generalize prepbufr adpupa converter

- src/gnssro/gnssro_bufr2ioda.py
- src/hdf5/atms_netcdf_hdf5_2ioda.py
- src/hdf5/tropics_2ioda.py
- src/pyiodaconv/def_jedi_utils.py
bring the TROPICS data converter in line with the ioda-converter library updates
Resolves #1342
> tropics converter update for libs

- CI/buildspec_clang.yml
- CI/buildspec_gnu.yml
- CI/buildspec_intel.yml
- Update to CI scripts (loading the modules via a different script)
> Update CI scripts for updated containers

- src/gsi_ncdiag/gsi_ncdiag.py
Our nightly picked up a bug in the Ozone converter code. TotalBias is an undefined variable.
> Pass TotalBias argument to Ozone.toGeovals

- test/CMakeLists.txt
Comment out bad ctest for a susbsequent PR to fix.
> comment out bad ctest for now

- src/bufr/BufrParser/Exports/Variables/SensorScanAngleVariable.cpp
- src/bufr/BufrParser/Query/QuerySet.cpp
- src/bufr/BufrParser/Query/ResultSet.cpp
- src/bufr/DataObject.h
- test/CMakeLists.txt
- test/testinput/bufr_ncep_prepbufr_aircft.yaml
- test/testoutput/prepbufr_adpupa_api.nc
- test/testoutput/rtma_ru.t0000z.aircft.tm00_nc004006.nc
- test/testoutput/rtma_ru.t0000z.aircft.tm00_nc004103.nc
Fixes failing ctests for ioda-converter BUFR code.
> Fix failing BUFR ctests.

- src/conventional/windborne_json2ioda.py
relocate the argument parsing to the end of the file
> relocate the argument parser to end of file

- test/testinput/bufr_filtering.yaml
- test/testinput/bufr_high_dims.yaml
- test/testinput/bufr_sfcshp.yaml
- test/testinput/bufr_splitting.yaml
- test/testoutput/bufr_sfcshp.nc
Provide a detailed description of what this PR does. What problem does it fix? What new capability does it add?
will finish long standing tasks for:  https://github.com/JCSDA-internal/ioda/issues/379
Resolves #1422
> update syntax to ioda v2
